# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

resample_multinomial_cpp <- function(n, weights) {
    .Call(`_bayesSSM_resample_multinomial_cpp`, n, weights)
}

resample_stratified_cpp <- function(n, weights) {
    .Call(`_bayesSSM_resample_stratified_cpp`, n, weights)
}

resample_systematic_cpp <- function(n, weights) {
    .Call(`_bayesSSM_resample_systematic_cpp`, n, weights)
}

